### PR TITLE
A bunch of shell scripts to help test xCAT high availibility

### PR DESCRIPTION
**Pull request by neo954**
* test-xcat-ha-00-restore-env.sh
   Restore the test environment to the shape of Red Hat Linux default install.
* test-xcat-ha-10-management-node-one.sh
   Run tests on xCAT management node one
* test-xcat-ha-20-management-node-two.sh
   Run tests on xCAT management node two
* test-xcat-ha.conf
   Configurations of the test environment

### CODE REVIEW

**Comment by neo954** [comment]
Refer to xcat2/xcat2-task-management#163

**Comment by zet809** [comment]
The scripts looks great, several question:
1. When to use test-xcat-ha-00-restore-env.sh?
2. For test-xcat-ha-10-management-node-one.sh and test-xcat-ha-20-management-node-two.sh, I think shall add some more description about what shall be done before running the cases.

**Comment by whowutwut** [comment]
I don't think this is the correct place to commit these scripts.  This is a tool for our internal test team to run HA testing... suggest one of the following internal repos: 

* https://github.ibm.com/xcat2/jenkins  or
* https://github.ibm.com/xcat2/automation_tools

1. `test-xcat-ha-00-restore-env.sh` - why bother with cleaning up an environment when we can use xCAT to re-provision a new one from scratch.   This is tailored  for rhels7, are you going to create new pkg list for each OS we support moving forward? Not very maintainable. 

2. `test-xcat-ha-10-management-node-one.sh` - For this one, suggest we create a generic postscript added to our internal repos that allows it to become a reusable asset for anyone on our internal team to call. 

3. `test-xcat-ha.conf`  this should be committed into our internal repos, not as sample tools for customers but really information in our internal test environment... don't think it should be here.

**Comment by neo954** [comment]
Moved to https://github.ibm.com/xcat2/automation_tools/pull/3

**Comment by neo954** [comment]
Thus, I will close this one.

**Comment by chuckbrazie** [comment]
I am out of the office until 07/16/2018.

I am out of the office until  Monday July 16.


Note: This is an automated response to your message  "Re:
[xcat2/xcat-extensions] A bunch of shell scripts to help test xCAT high
availibility (#26)" sent on 7/11/18 6:33:28 AM.

This is the only notification you will receive while this person is away.

**Comment by chuckbrazie** [comment]
I am out of the office until 07/16/2018.

I am out of the office until  Monday July 16.


Note: This is an automated response to your message  "Re:
[xcat2/xcat-extensions] A bunch of shell scripts to help test xCAT high
availibility (#26)" sent on 7/11/18 6:33:17 AM.

This is the only notification you will receive while this person is away.

**Pull request closed without merging**
